version: "3"
services:
 web:
    image: pet-shop-security:v5
    container_name: pet-shop-security
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dsv}
      - SPRING_DATASOURCE.URL=jdbc:postgresql://db:5432/pet-shop-security
    ports: 
      - '8080:8080'
    networks:
      - pet-shop-security-network
    depends_on: db
 db: 
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=pet-shop-security
    networks:
      - pet-shop-security-network
   
networks:
 pet-shop-security-network:
   driver: bridge