apiVersion: v1
metadata:
 name: pet-shop-security-service
kind: Service
spec:
  selector:
   app: pet-shop-security
  ports:
   - name: http #nome da porta para acessar o container docker dentro do pod, é o mesmo nome configurado no objeto deployment
     port: 80 #porta externa de acesso ao serviço
     targetPort: 8080 #porta para acessar o container docker dentro do pod, é a mesma porta configurada no objeto deployment
